### ISSUE TITLE
/chap_json2csv.py  not found

### ISSUE THREAD

**Issue by ncoudray** [channotation/chap#10]
Hi, 
Thanks for making that program available.
I tried to convert the json to csv, but it looks like the "/chap_json2csv.py " mentioned in the documentation is not part of the latest version. Is it possible to receive it in some way?

Thanks,
Best,
Nicolas

**Comment by ncoudray** [comment]
Ah, I found a way to write my own script with your instructions....

**Comment by Inniag** [comment]
Hi Nicolas,
I'm glad to hear you already found a workaround yourself. However, in case someone else finds this thread I would mention that the script is already on the Master branch of this repository and can be found [here](https://github.com/channotation/chap/blob/master/scripts/plotting/Python/chap_json2csv.py). 
Best wishes!
