### ISSUE TITLE
Cmake error while compiling from the source 

### ISSUE THREAD

**Issue by BDehury85** [channotation/chap#14]
CMakeFiles/googletest.dir/build.make:90: recipe for target 'googletest-prefix/src/googletest-stamp/googletest-download' failed
make[2]: *** [googletest-prefix/src/googletest-stamp/googletest-download] Error 1
CMakeFiles/Makefile2:429: recipe for target 'CMakeFiles/googletest.dir/all' failed
make[1]: *** [CMakeFiles/googletest.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Inniag** [comment]
Closing this as duplicate of #15 .
