### ISSUE TITLE
Using NAMD trajectories?

### ISSUE THREAD

**Issue by winsvern** [channotation/chap#24]
I have some trajectories produced using NAMD.  I have tried to convert these to a form that will work in CHAP and failed.  Is there a way to convert these trajectories to a format that is readable by CHAP?

Thank  you in advance.

Vern Winston

**Comment by Inniag** [comment]
I've never worked with NAMD, but I have successfully converted `*.dcd` trajectories produced by OpenMM to Gromacs' `*.xtc` format using the [MDAnalysis](https://www.mdanalysis.org/) library. The converted trajectory can then be used as input for the `-f` flag of CHAP. A corresponding PDB file can be used for the `-s` flag.

A conversion script might look like this:

```Python
import MDAnalysis as mda

# load NAMD trajectory, PDB file is needed to define topology
u = mda.Universe("structure.pdb", "trajectory.dcd")

# select all particles
system = u.select_atoms("all")

# write to XTC trajectory
with mda.Writer("converted_trajectory.xtc", system.n_atoms) as w:
    for ts in u.trajectory:
        w.write(system)
```

Hope this helps!

**Comment by winsvern** [comment]
The script works perfectly (after I got openMM and MDanalysis up and
running).  The converted trajectory and pdb file are accepted by CHAP.
Progress.  Now I have to fix some problems with my NAMD run, and will be on
my way.  (Eventually I want to convert this project to GROMACS, and that
would make everything easier, but that is for another day)

Thank you again.  You saved me a huge amount of time.

Vern Winston

**Comment by Inniag** [comment]
Glad I could help! I hope CHAP proves useful for your project. Good luck with your NAMD to Gromacs migration.
