### ISSUE TITLE
Imported target "libgromacs" includes non-existent path

### ISSUE THREAD

**Issue by GeraZerbetto** [channotation/chap#28]
Hi everyone!
I am having some trouble at the cmake step, during the compilation
Here I attach the output. Gromacs 2020 is installed in /usr/local/gromacs
Thanks in advance!
Gera!

`cmake ..

-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Boost version: 1.65.1
-- Found LAPACKE: /usr/include/x86_64-linux-gnu  
-- Found GROMACS: 2020.2
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
CMake Error at CMakeLists.txt:155 (add_executable):
  Target "chap" links to target "OpenMP::OpenMP_CXX" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at test/CMakeLists.txt:42 (add_executable):
  Target "runAllTests" links to target "OpenMP::OpenMP_CXX" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error in CMakeLists.txt:
  Imported target "libgromacs" includes non-existent path

    "/usr/local/gromacs/COMPONENT"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in CMakeLists.txt:
  Imported target "libgromacs" includes non-existent path

    "/usr/local/gromacs/COMPONENT"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in test/CMakeLists.txt:
  Imported target "libgromacs" includes non-existent path

    "/usr/local/gromacs/COMPONENT"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in test/CMakeLists.txt:
  Imported target "libgromacs" includes non-existent path

    "/usr/local/gromacs/COMPONENT"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

-- Generating done
-- Build files have been written to: /home/geraz/chap-version_0_9_1/build`

**Comment by Inniag** [comment]
Hi Gera,

It looks like this issue is caused by trying to install CHAP into an environment that is different from the one the underlying Gromacs was installed into. In particular, OpenMP seems to not be available. Always make sure that you use the same libraries and compilers for installing CHAP and Gromacs.

I also need to point out that CHAP currently does not work with Gromacs 2020 due to some changes in `libgromacs` that still need to be included into its code base. For the time being you should use Gromacs 2016 or 2018.

Hope this helps!
