### ISSUE TITLE
ERROR CMAKE

### ISSUE THREAD

**Issue by DANIELUAB** [channotation/chap#31]
Hi, i have te following error after doing:
tar -xvzf version_0_8_0.tar.gz
cd chap-version_0_8_0
mkdir build
cd build
cmake ..
make

'Error': TopologyInformation’ in namespace ‘gmx’ does not name a type
I am new using gromacs and this package

**Comment by Inniag** [comment]
Which version of Gromacs are you using?

**Comment by Inniag** [comment]
Closing as no details have been provided.
